In [3]:
### convert all to list
w = open("cat.txt")
data = w.read()
data


'Apple   1.99    Round\nBanana  0.99    Curved\nOrange  2.49    Spherical\nGrapes  3.99    Oval\nStrawberry  0.25    Conical\nMango   2.79    Oval\nWatermelon  5.49    Oval\nPineapple   2.99    Cylindrical\nPeach   1.49    Round\nKiwi    1.89    Oval\n'

In [4]:
data.split("\n")

['Apple   1.99    Round',
 'Banana  0.99    Curved',
 'Orange  2.49    Spherical',
 'Grapes  3.99    Oval',
 'Strawberry  0.25    Conical',
 'Mango   2.79    Oval',
 'Watermelon  5.49    Oval',
 'Pineapple   2.99    Cylindrical',
 'Peach   1.49    Round',
 'Kiwi    1.89    Oval',
 '']

In [27]:
fruits, price, shape = [],[],[]
for each in data.split("\n"):
    orange = each.split("  ")[:-]
    print(orange)

SyntaxError: invalid syntax (2072083160.py, line 3)

In [28]:
#
import json

# Sample fruit data in a dictionary
fruit_data = [
    {
        "name": "Apple",
        "price": 1.99,
        "shape": "Round"
    },
    {
        "name": "Banana",
        "price": 0.99,
        "shape": "Curved"
    },
    {
        "name": "Orange",
        "price": 2.49,
        "shape": "Spherical"
    },
    {
        "name": "Grapes",
        "price": 3.99,
        "shape": "Oval"
    },
    {
        "name": "Strawberry",
        "price": 0.25,
        "shape": "Conical"
    },
    {
        "name": "Mango",
        "price": 2.79,
        "shape": "Oval"
    },
    {
        "name": "Watermelon",
        "price": 5.49,
        "shape": "Oval"
    },
    {
        "name": "Pineapple",
        "price": 2.99,
        "shape": "Cylindrical"
    },
    {
        "name": "Peach",
        "price": 1.49,
        "shape": "Round"
    },
    {
        "name": "Kiwi",
        "price": 1.89,
        "shape": "Oval"
    }
]

# Save the fruit data as a JSON file
with open('fruits.json', 'w') as json_file:
    json.dump(fruit_data, json_file, indent=4)


In [33]:
with open('fruits.json', 'r') as json_file:
    # Load the JSON data from the file
    blarh = json.load(json_file)

In [45]:
for pyth in blarh:
    name=pyth["name"]
    price=pyth["price"]
    shape=pyth["shape"]
    print("the name of the fruit is",name,"and price is",price,"and shape is",shape)


the name of the fruit is Apple and price is 1.99 and shape is Round
the name of the fruit is Banana and price is 0.99 and shape is Curved
the name of the fruit is Orange and price is 2.49 and shape is Spherical
the name of the fruit is Grapes and price is 3.99 and shape is Oval
the name of the fruit is Strawberry and price is 0.25 and shape is Conical
the name of the fruit is Mango and price is 2.79 and shape is Oval
the name of the fruit is Watermelon and price is 5.49 and shape is Oval
the name of the fruit is Pineapple and price is 2.99 and shape is Cylindrical
the name of the fruit is Peach and price is 1.49 and shape is Round
the name of the fruit is Kiwi and price is 1.89 and shape is Oval


 the name of the fruit is Apple and price is 1.99 and shape is Round
the name of the fruit is Banana and price is 0.99 and shape is Curved
the name of the fruit is Orange and price is 2.49 and shape is Spherical
the name of the fruit is Grapes and price is 3.99 and shape is Oval
the name of the fruit is Strawberry and price is 0.25 and shape is Conical
the name of the fruit is Mango and price is 2.79 and shape is Oval
the name of the fruit is Watermelon and price is 5.49 and shape is Oval
the name of the fruit is Pineapple and price is 2.99 and shape is Cylindrical
the name of the fruit is Peach and price is 1.49 and shape is Round
the name of the fruit is Kiwi and price is 1.89 and shape is Oval

In [49]:
data = ""
s = " "
new_lin = "\n"
for each in blarh:
    data+= each['name']+s+str(each['price'])+s+each['shape']+new_lin
    


In [51]:
print(data)

Apple 1.99 Round
Banana 0.99 Curved
Orange 2.49 Spherical
Grapes 3.99 Oval
Strawberry 0.25 Conical
Mango 2.79 Oval
Watermelon 5.49 Oval
Pineapple 2.99 Cylindrical
Peach 1.49 Round
Kiwi 1.89 Oval



In [52]:
"hello world"

'hello world'

In [53]:
print("hello world")

hello world


In [54]:
blarh

[{'name': 'Apple', 'price': 1.99, 'shape': 'Round'},
 {'name': 'Banana', 'price': 0.99, 'shape': 'Curved'},
 {'name': 'Orange', 'price': 2.49, 'shape': 'Spherical'},
 {'name': 'Grapes', 'price': 3.99, 'shape': 'Oval'},
 {'name': 'Strawberry', 'price': 0.25, 'shape': 'Conical'},
 {'name': 'Mango', 'price': 2.79, 'shape': 'Oval'},
 {'name': 'Watermelon', 'price': 5.49, 'shape': 'Oval'},
 {'name': 'Pineapple', 'price': 2.99, 'shape': 'Cylindrical'},
 {'name': 'Peach', 'price': 1.49, 'shape': 'Round'},
 {'name': 'Kiwi', 'price': 1.89, 'shape': 'Oval'}]

['Apple 1.99 Round',
 'Banana 0.99 Curved',
 'Orange 2.49 Spherical',
 'Grapes 3.99 Oval',
 'Strawberry 0.25 Conical',
 'Mango 2.79 Oval',
 'Watermelon 5.49 Oval',
 'Pineapple 2.99 Cylindrical',
 'Peach 1.49 Round',
 'Kiwi 1.89 Oval',
 '']

In [66]:
## make list
listi=[]
## run for loop
for g in data.split("\n"):
    # temp ={}
    tem['name'] = g.split

### make temp dict
## update dictionary with dt

Apple 1.99 Round
Banana 0.99 Curved
Orange 2.49 Spherical
Grapes 3.99 Oval
Strawberry 0.25 Conical
Mango 2.79 Oval
Watermelon 5.49 Oval
Pineapple 2.99 Cylindrical
Peach 1.49 Round
Kiwi 1.89 Oval



In [67]:
spam = input("say a number")
if spam == 1:
    print("hello")
if spam == 2:
    print("Howdy")
else:
    print("Greetings!")

Greetings!


In [72]:
for each in range(11):
    print(each)

0
1
2
3
4
5
6
7
8
9
10


In [2]:
x=0
while x < 10:
    x=x+1
    print(x)

1
2
3
4
5
6
7
8
9
10


In [4]:
def bacon(spam):
    print(spam)
    pass
bacon(10)

10


Write a function that takes a list value as an argument and returns
a string with all the items separated by a comma and a space, with and
inserted before the last item. For example, passing the previous spam list to
the function would return 'apples, bananas, tofu, and cats'. But your function should be able to work with any list value passed to it.

spam = ['apples', 'bananas', 'tofu', 'cats']

In [5]:
spam = ['apples', 'bananas', 'tofu', 'cats']

In [8]:
def function(argument):
    s = ""
    for eager in argument:
        s = s + "  "+eager
    return s

In [12]:
function(spam)

'  apples  bananas  tofu  cats'

In [10]:
grid = [['.', '.', '.', '.', '.', '.'],
 ['.', 'O', 'O', '.', '.', '.'],
 ['O', 'O', 'O', 'O', '.', '.'],
 ['O', 'O', 'O', 'O', 'O', '.'],
 ['.', 'O', 'O', 'O', 'O', 'O'],
 ['O', 'O', 'O', 'O', 'O', '.'],
 ['O', 'O', 'O', 'O', '.', '.'],
 ['.', 'O', 'O', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.']]

In [15]:
def function100(argument100):
    s = ""
    for each in argument100:
        for i in each:
             s = s + "  "+i
        s = s + "\n"
    return s

In [17]:
s = function100(grid)
print(s)

  .  .  .  .  .  .
  .  O  O  .  .  .
  O  O  O  O  .  .
  O  O  O  O  O  .
  .  O  O  O  O  O
  O  O  O  O  O  .
  O  O  O  O  .  .
  .  O  O  .  .  .
  .  .  .  .  .  .

